### ISSUE TITLE
[BUG] PlayerInteractEvent

### ISSUE THREAD

**Issue by DavidRSM29** [PluginBugs/Issues-PocketMobs#6]
**Describe the bug**
Error on the console.

**To Reproduce**
1. Use a key from GoldenCrates to open a crate.
2. Then the error appears on the console

**Expected behavior**
No errors on the console.

**Info (please complete the following information):**
 - Server version: Tuinity 1.16.5
 - Client version: 1.16.5
 - Plugin version: 1.0.28

**Additional context**
https://pastebin.com/LsCdmvcA **- Error**

**Comment by LoneDev6** [comment]
it's already fixed in version 1.0.30

**Comment by DavidRSM29** [comment]
still present on 1.0.31 https://pastebin.com/mJZ1Hvdp same error with the same action explained above.
